### ISSUE TITLE
Make the carousel responsive (discussion)

### ISSUE THREAD

**Issue by makbeta** [tomhrtly/flexCarousel.js#6]
@tomhrtly 
I'm opening up an feature request to discuss how to best approach adding in responsive options. 

Pardon if I'm going over the obvious but wanted to lay out my whole thought process here. 

Since the slider probably will have variously different properties based on the screen size, the user should have an ability to set/modify each option/setting for each breakpoint.  To make that work with already well-functioning core functions we should just destroy an existing slideshow and build a new one when screen-size changes.  To prevent the breakpoint from completely overriding original settings, which includes breakpoint settings themselves, they should be saved for later use.

I considered coming up with a code that would fit here but realized that I may be reinventing the wheel.  I looked into how the slick slideshow does it, which is a slideshow that handles responsive states already. The author there does that exact same thing, plus maybe adds a few more bells and whistles. [See function checkResponsive, line 595](https://github.com/kenwheeler/slick/blob/master/slick/slick.js) for the "swap" of options.

I hope this is helpful, do let me know if you don't find it useful or have follow up questions.

**Comment by tomhrtly** [comment]
@makbeta 

> Since the slider probably will have variously different properties based on the screen size, the user should have an ability to set/modify each option/setting for each breakpoint. To make that work with already well-functioning core functions we should just destroy an existing slideshow and build a new one when screen-size changes. To prevent the breakpoint from completely overriding original settings, which includes breakpoint settings themselves, they should be saved for later use.

Yes, that's the current plan, I think a responsive option that is an array with multiple objects inside will be the easiest and simplest way for users to change the options for different breakpoints. I have started working on this in the `options-responsive` branch but I still have quite a bit todo.

I'm either thinking that there should be a function to re-init the carousel when the breakpoint changes with the new options or change the object that gets passed when initializing. I believe the former will be the most straightforward approach but I'll wait and see.

> I looked into how the slick slideshow does it, which is a slideshow that handles responsive states already. The author there does that exact same thing, plus maybe adds a few more bells and whistles. See function checkResponsive, line 595 for the "swap" of options.

Yes I've taken a look at the source code for slick, there's definitely some inspiration to be taken from this!

I will leave this issue open until the responsive option is complete in case anyone else would like to leave feedback or comments.

**Comment by makbeta** [comment]
@tomhrtly 
I took a stab at starting the responsive option. The source code is here:
https://github.com/makbeta/flexCarousel.js/blob/options-responsive/src/flexCarousel.js

What I did:
1. Added destroy function that just replaces the full slideshow with the original code.
2. Added an outline for resizing function that would destroy/rebuild the slideshow when the breakpoint changes.

I think for the next steps it's best to outline how breakpoints & their settings would be stored, I was thinking of following the slick option as well, where responsive would be an array of breakpoint values and options. Although not 100% sure about the best way to handle default option, if it should be included something that is set by default and assumes that it's a breakpoint of 0px and greater. 

P.S. I needed a mobile solution for the live site ASAP and didn't have resources to fully built out the responsiveness, so I just added a destroy/rebuild option for one preset breakpoint. The site where I'm using this plugin is https://ontariospca.ca/, the destroy option may not be live yet.

**Comment by tomhrtly** [comment]
@makbeta Apologies for the very long delay in replying to you, been very busy these past few months. I've made flexCarousel.js a dependency free JavaScript plugin that now supports responsive options.

I'm going to be working on adding documentation in the following weeks and squashing some bugs that I've found along the way. Any feedback would be great!
