### ISSUE TITLE
Roll to start

### ISSUE THREAD

**Issue by centurianii** [tomhrtly/flexCarousel.js#7]
**Describe the feature**
Suppose the following options:

```
$(document).ready(function() {
   $('.some-class').flexCarousel({
      slidesVisible: 3,
      arrowsOverlay: false
});
});
```

**To Reproduce**
Clicking right arrow I can finally see:
1. the 1st image after the 4th!(?)

Clicking on to circles:
2. in every direction I click the relevant image goes straight to the left thus, permitting images from the start to appear to the right!(?).

I can also see ghosts in code of the original images as an effort to close probably previous logical "gaps". 

**Expected behavior**
1. Carousel should roll to start otherwise the user gets wrong impression.  Remove "ghosts".

2. Align next image to the right (not left) otherwise the user gets wrong impression; previous image aligns correctly as it is to the left.

**jsFiddle**
https://jsfiddle.net/centurianii/q0hLjfvc/

**Comment by tomhrtly** [comment]
Could you explain what you mean by "Carousel should roll to start otherwise the user gets wrong impression"? Are you talking about an animation for when the carousel is initialised?

For the circles, when clicking on a circle this changes the `order` property of the slide to the index of the circle you clicked on. I do see this looks buggy when if you are on the first slide and then click the last circle.

I'm working on rebuilding the circles option to take advantage of the `transform` property so that the slides look more like they are sliding rather than just "switching" places in the DOM.

For the issue regarding seeing the first slide after the last slide in your carousel, this is because the carousel's slides continuously loop through the `order` position. Are you wanting a feature which would disable the user from clicking the next button when they reach the last slide?

Lastly, you mentioned gaps in the slides. There is a 16px padding for each slide container. In your case to remove any gaps, you would need to remove the padding through the source files and then increase the height of your carousel so that the images can reach the edge of their containers.

**Comment by centurianii** [comment]
> Could you explain what you mean by "Carousel should roll to start otherwise the user gets wrong impression"? Are you talking about an animation for when the carousel is initialised?

Suppose slides A, B, C, D. I move from C -> D. 
Now I am at D. If I click right arrow I can see A again coming from the right! My impression is that this is a new slide - meybe E? who knows. I keep moving around until I realized that the slider just moves in a circular fashion but with no sign when this "recycle" or "back to start" happens.

> Are you wanting a feature which would disable the user from clicking the next button when they reach the last slide?

Yes, that's the idea!

Now, let's move to the "circles" behavior. When I click the circle the **relevant** slide aligns straight to the left! That's buggy and leads to buggy behavior when there are more than one slides.

The correct behavior is:

- does the circle represents a hidden image to the right? align in to the right

- does the circle represents a hidden image to the left? align in to the left

- does the circle represents a visible image? do nothing (moving things will disorientate the user).

Of course after 2nd thoughts and looking again owl carousel I had an epiphany: circles **should not** represent slides but indeed they are a paging system.

Let me explain this. Suppose the slider allowed space on screen it's 3 slides and we have 8 (3 by 3 is not 8 nor 3 by 2) so, how many pages do we have? actually 3 and we'll use this idea later.

Now, as it's currently implemented when I click 2nd circle it goes straight to the left and the 4th enters from the right. Not so bad but when I touch 7th circle I can see on my screen 7th and 8th. Why the last place remains empty? My previous screen of slides 6-7-8 would be just fine occupying the full space! How did I reached that full-screen? when I pressed 6th circle.

This example got me thinking. Circles seem too many and most of the time they do the same job. We don't need circle 7 or 8, 6 is just fine. On the other direction, we don't need 1 or 2, 3 is just fine. But wait, what if the capacity was 5 slides? Now it starts looking that circle does **not** represent image but a page maybe?

In the above example we just need 3 circles with a capacity of 3 out of 8 slides.

Similarly, we need 2 circles with a capacity of 5 out of 8 or, as equation: `pages = slides % capacity + 1` even if `slides < capacity` (of course in that situation you have to decide between align left/right/center).

The only difference I can see between a paging system and slider's circles is the behavior at **edge** conditions: when 5 slides fit in my screen out of 8 then moving to next (last) page in a paging system (like data tables) would show me 6-7-8 but in the slider situation it's better to see again 4-5 and the last 6-7-8 slides.

That's the most of it :)

**Comment by centurianii** [comment]
As a side note: one can implement a slider from a completely different approach (as I did) with even much lesser code so, there is no _precise_ or _correct_ recipe here....

**Comment by tomhrtly** [comment]
> Suppose slides A, B, C, D. I move from C -> D.
Now I am at D. If I click right arrow I can see A again coming from the right! My impression is that this is a new slide - meybe E? who knows. I keep moving around until I realized that the slider just moves in a circular fashion but with no sign when this "recycle" or "back to start" happens.

Thanks for that! I understand your point now, I'm just thinking what else would be useful to the user to let them know they have reached the end of the carousel, I think the circles that have the active state does this quite well, what do you think?

In regards to an option that would disable either arrow button at the beginning or end of the carousel, I can take a look at this for you and see what I can come up with for 0.3.0 which I have started on the `vanilla-js` branch.

Thanks for your detailed explanation of the circles, I do agree that they need to work more smoothly to give the user the idea of "rolling" to a specific slide. I also think your view of the circles to be a paging system is very interesting and I believe it would work nicely with the `slidesPerPage` option that was merged a [few weeks ago](https://github.com/tomhrtly/flexCarousel.js/pull/4).

I've started rebuilding the carousel plugin with just vanilla JS and once I've got the basic carousel functionality up and running with no hiccups, I'll take a look at making the `circles` option a lot more user-friendly and smoother. I may also add a `loop` option in 0.3.0 and bump the vanilla JS version up to 0.4.0.

**Comment by centurianii** [comment]
Whatever path you take don't forget to address testing strategy at the VERY beginning; it does pay off later!

I regret to say that - I like many others - love object-oriented code but javascript is completely handicapped to handle this programming paradigm when it comes to testing (I need php's reflection in js asap!).

So unfortunately, Node and it's environment is the only way with a programming style of function under function that resembles 80's (my opinion here). I also don't believe that unit testing is a panacea as they are not functional tests at their own nature so, even if someone put tons of work to unit test it's always half the work and half the road that he should take.

I actually made my own testing tool to test my js code and keep testing cases organized, I call it [evaluator](https://centurianii.github.io/g3/) and helped me a lot to test very complex code that I intend to dispatch with proprietary license (easy to add mocha-chai-sinon for browser [testing](https://codepen.io/centurianii/pen/BMGOOG)).

Lastly, if at some point you bump on features like mobile devices, touch scrolling etc. - a really pain on the ash - I would propose either do nothing (i.e. enable scrollbars!) or use [interact](https://interactjs.io/) (no jquery mobile or jquery UI because such carousel is already there - I think - so why duplicate? Most of the time devs make projects to propose alternatives right?).

**Comment by tomhrtly** [comment]
@centurianii 
Thanks for your advice and help, I'm hoping to get this feature finished hopefully sometime within the next few weeks, very busy at my job lately.

I'll take a close look at your testing tool soon, it sounds like it will be a big help so thanks for letting me know! It's also an interesting point you made regarding interact.js, that sounds like it will be a lot easier to implement touch scrolling etc for mobile that way.
